services:
  openbao:
    image: ghcr.io/openbao/openbao:latest
    container_name: openbao
    ports:
      - "8200:8200"
    environment:
      - OPENBAO_ADDR=0.0.0.0:8200
      - OPENBAO_API_ADDR=0.0.0.0:8200
      - OPENBAO_DEV_ROOT_TOKEN_ID=root
      - OPENBAO_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev
    volumes:
      - ./vault/data:/openbao/file
    networks:
        - pdns-network 
  db:
    image: mariadb:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - pdns-network
  pdns:
    image: psitrax/powerdns
    platform: linux/amd64
    container_name: pdns
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    environment:
      MYSQL_USER: root
      MYSQL_PASS: root
      MYSQL_PORT: 3306
      API_KEY:
    command: >
      --cache-ttl=120
      --allow-axfr-ips=127.0.0.1,123.1.2.3
      --webserver=yes
      --webserver-address=0.0.0.0
      --api=yes
      --api-key=APIKEY
      --webserver-allow-from=0.0.0.0/0
    depends_on:
      - db
    networks:
      - pdns-network
      
networks:
  pdns-network:
    driver: bridge 