services:
  openbao:
    image: ghcr.io/openbao/openbao:latest
    container_name: openbao
    ports:
      - "8200:8200"
    environment:
      - OPENBAO_ADDR=0.0.0.0:8200
      - OPENBAO_API_ADDR=0.0.0.0:8200
      - OPENBAO_DEV_ROOT_TOKEN_ID=root
      - OPENBAO_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: server -dev
    volumes:
      - ./vault/data:/openbao/file