vault_addr = "http://127.0.0.1:8200"
unseal_keys = ["r/X8GJbs7zMph/hjPW00aZlqu4YbRfUhDtHHOU3aqOc="]
pki_mount_path = "pkilocal"
ca_pem_path = "./ca_root/rootCA.pem"
ca_key_path = "./ca_root/rootCA-key.pem"
allowed_domain = "example.local"
vault_token = "s.la54mKfrv5KFkeuZmaNk3gL5"
powerdns_addr = "http://127.0.0.1:8081/api/v1" 
powerdns_api_key = "APIKEY"
